core/Run.ml
core/Store.ml
core/Testo.ml
core/Testo.mli
core/Types.ml
tests/Meta_test.ml
tests/snapshots/testo_dummy_failing_tests/189ed1da5108/stdout

The new policy is:
> Exit with a nonzero status if any user action is needed.
Previously, the exit status could be 0 (success) even if some new tests didn't have their output approved and recorded as snapshots.
Also, now we print a reason for a test failing when it's not already clear - this indicates if the test failed due to an exception or due to the output being wrong.

Exit with a nonzero code if any test needs its output approved

---

core/Testo.ml
core/Testo.mli
tests/Test.ml
tests/snapshots/testo_meta_tests/fccf02a5c37e/stdxxx
tests/snapshots/testo_tests/065cc54b852b/stderr

The goal is to only mask the variable parts of a temporary path that shows up in the output of a test rather than the whole path.
Common cases are depths of 0 or 1:
* depth = 0: `/tmp/hello` -> `<MASKED>hello`
* depth = 1: `/tmp/hello` -> `<MASKED>`; `/tmp/ab43987f1/hello` -> `<MASKED>hello`
Depth = 1 is now the default which will break existing snapshots. I believe it's the preferred setting most of the time, though. The old behavior was equivalent to masking the whole path i.e. unlimited depth (`~depth:None`).

Add an optional 'depth' parameter to the function for masking temp paths

---

core/Testo.ml
core/Testo.mli
tests/Meta_test.ml
tests/Test.ml

This changes the interface and behavior of `mask_temp_paths` so as to show more details about the masked path. This replaces the `mask` option by a more general `replace` option in both `mask_temp_paths` and `mask_pcre_pattern`.

Improve mask_temp_paths

---

core/Cmd.ml
core/Run.ml
core/Run.mli
tests/Meta_test.ml
tests/snapshots/testo_meta_tests/fccf02a5c37e/stdxxx

The `--short` option is gone and its behavior is now the default which is to print only the tests that need attention, omitting the tests that were successful or skipped. `--all`/`-a` prints all the tests like before. The default output now consists of one line per test. `--long`/`-l` prints tests in the long format like before.
The options `-l` and `-a` were chosen to remind us of the same familiar options of the `ls` command.
This is not quite an interactive test browser (https://github.com/semgrep/testo/issues/39) but it was easy to implement.

Switch to a compact output by default for the `status` subcommand

---

.circleci/setup
core/Helpers.ml
core/Run.ml
tests/Test.ml
tests/snapshots/testo_tests/065cc54b852b/stderr

This includes all the necessary fixes for CI checks to work correctly with ocaml 4.08 in addition to the ocaml 4.14 (TODO: update https://github.com/mjambon/ocaml-layer to provide an image for ocaml 5).

Backward compatibility with ocaml 4.08

---

CHANGES.md
core/Testo.ml
tests/Test.ml
tests/snapshots/testo_meta_tests/fccf02a5c37e/stdxxx

(or backslash on Windows).
This a partial redo of https://github.com/semgrep/testo/pull/42
PR checklist:

Fix 'mask_temp_paths' for when the temp folder path ends with a slash

---

core/Testo.ml
tests/Test.ml

Don't mask temporary paths that occur as substrings of other paths

---

.circleci/config.yml

This adds a Semgrep scan with CircleCI by following the official instructions. No custom semgrep build, no custom rules for this repo.
PR checklist:

Add CircleCI config to have the repo scanned by Semgrep

---

.circleci/config.yml
Makefile
docs/index.html
docs/tutorial/index.html
docsrc/Makefile
docsrc/index.md
docsrc/tutorial/.gitignore
docsrc/tutorial/dune
docsrc/tutorial/index.md
docsrc/tutorial/run-tutorial

Will be visible at https://semgrep.github.io/testo/tutorial/ after merging.
`make doc` will check that the provided script `run-tutorial` works. There is no CI check for it yet.
PR checklist:

Add a tutorial

---

core/Cmd.ml
core/Run.ml
core/Run.mli
tests/snapshots/testo_meta_tests/fccf02a5c37e/stdxxx

Closes #81
The output of `run` now looks like this in the case of test failures:
PR checklist:

Print compact list of failed tests at the end of each run

---

core/Cmd.ml
core/Run.ml
core/Run.mli
tests/Test.ml
tests/snapshots/testo_meta_tests/fccf02a5c37e/stdxxx
util/Slice.ml
util/Slice.mli

This allows splitting a CI job into multiple jobs using e.g.
```
./test --slice 1/4
./test --slice 2/4
./test --slice 3/4
./test --slice 4/4
```
It is also the first step toward a `-j` option that does the splitting for us and merges the results in an orderly fashion (#8).
PR checklist:

Add --slice option for distributed/parallel runs

---

tests/snapshots/testo_meta_tests/fccf02a5c37e/stdxxx
util/Diff.ml

A diff was incorrectly shown as follows:
```
context line 1
-deleted line
+added line
context line 2
```
The context lines are now correctly indented so as to align with the +/- lines:
```
context line 1
-deleted line
+added line
context line 2
```
PR checklist:

Add missing space leading the lines of context in diff output

---

core/Run.ml
core/Store.ml
core/Store.mli
tests/Failing_test.ml
tests/snapshots/testo_failing_tests/b6c9cb0d2045/name

Fixes #93 
* When a test fails with an exception but stderr is captured a snapshot, the exception is now shown (in red) even if stderr is captured as a snapshot and not shown.
* When a test that's expected to fail succeeds, the exception is now shown (in green) in verbose mode (`status -v`).
PR checklist:

Show exceptions raised by tests independently of showing/hiding stderr

---

core/Run.ml
core/Store.ml

This fixes a storage bug when running exported tests in Alcotest.
e.g.
``` ┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        fa42a29dc6d2 Language Server (e2e)          0   Test LS.       │
└──────────────────────────────────────────────────────────────────────────────┘
[exception] Error: Missing initialization call: Testo.init ()
Logs saved to `/__w/semgrep-proprietary/semgrep-proprietary/js/tests/_build/_tests/semgrep-js/fa42a29dc6d2 Language Server U+0028e2eU+0029.000.output'.
```
We don't have tests for the Alcotest export. For now, errors are caught in the semgrep repo where Alcotest is used to run some tests in JavaScript.
PR checklist:
Check out [`CONTRIBUTING.md`](https://github.com/semgrep/testo/blob/main/CONTRIBUTING.md) for more …

Fix alcotest export

---

core/Run.ml
core/Store.ml
core/Testo.ml
core/Testo.mli
core/Types.ml
tests/Test.ml
tests/snapshots/test-alcotest/7a153e9510c7/name
tests/snapshots/test-alcotest/bf36d37e7d10/name
tests/snapshots/testo_meta_tests/fccf02a5c37e/stdxxx
util/Style.ml

Closes #96 
We now also request a reason when skipping a test.
Closes #92 
PR checklist:

Add option to force a test to run alone (not concurrently with other tests)

---

dune-project
scripts/dev-setup-alpine
testo-diff.opam
testo-util.opam

The CI checks hadn't run in 3 months since the semgrep organization changed how users log into GitHub. I re-enabled the CircleCI checks and found that they were failing. This PR fixes two errors:
* one problem with how `pre-commit` (a Python application) was installed;
* a missing opam dependency in the dune-project file and the derived opam files
The tests now pass for the legacy build (OCaml 4.08) and fail for OCaml 5.2.1. I'll fix this in another PR.
PR checklist:

Fix CI environment

---

CHANGES.md
core/Cmd.ml
core/Run.ml
core/Run.mli
tests/Meta_test.ml
util/lib/Helpers.ml
util/lib/Helpers.mli

Allow multiple '-s' substring search queries in the same command

---

CHANGES.md
core/Cmd.ml
core/Run.ml
core/Run.mli
tests/Meta_test.ml
tests/snapshots/testo_meta_tests/a1982e6b3f31/stdxxx
tests/snapshots/testo_meta_tests/f69772f11d92/stdxxx
tests/snapshots/testo_meta_tests/fccf02a5c37e/stdxxx

This PR adds an option `--expert` for not showing messages targeted at new users. The legend for the test statuses can be hidden with this option, resulting in more compact output. The test command can be aliased to `./test --expert` for everyday use.
I also added a line encouraging the user to consult `--help`.
See the discussion at #109 
Closes #109 
PR checklist:

Hide legend with --expert

---

CHANGES.md
core/Cmd.ml

When run on Windows, tests are liable to encounter tracebacks like
```
test.exe: internal error, uncaught exception:
Invalid_argument("Sys.signal: unavailable signal")
Raised by primitive operation at Stdlib__Sys.set_signal in file "sys.ml.in", line 82, characters 39-63
Called from Testo__Cmd.run_with_conf in file "OSS/libs/testo/core/Cmd.ml", line 97, characters 29-50
Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
```
Because `Sys.signal` is not available on Windows.
Testing locally on my Windows VM has indicated that gating this on Windows allows tests to run correctly.
PR checklist:
Check out [`CONTRIBUTING.md`](https://github.com/semgrep/testo/blob/main/ …

fix(windows): don't catch sigpipe on Windows

---

CHANGES.md
core/Store.ml

The functions that use this combinator may try to delete the [filename]. In particular, this is done in [Temp_file.with_temp_file](https://github.com/semgrep/testo/blob/324883471634eba92b1d9608b298991bee3d67b4/core/Temp_file.ml#L9-L20). It is possible that some other part of the program maintaines a handle into the file when we call `Sys.remove`. This works without any problems on Linux and Mac, but on Windows it currently produces a permission error, such as
```
[10.14][ERROR]: Error: exception Error: Internal error in test framework: exception raised by 'finally': Sys_error("C:\\opam\\.cygwin\\root\\tmp\\testo-958f77.out: Permission denied")
Raised by primitive operation at Testo__Temp_file.with_temp_file.(fun) in file "OSS/libs/testo/core/Temp_file.ml", line 19, characters 26-43
Called …
```

fix(windows): make `with_redirect_fd_to_file` Windows compatible

---

.gitignore

I created a local switch for testo and saw that `_opam` appeared in my git diff. I've added it to `.gitignore`.
PR checklist:

Add _opam to .gitignore

---

CHANGES.md
core/Cmd.ml
core/Run.ml
core/Run.mli
core/Store.ml
core/Store.mli
tests/Meta_test.ml
tests/snapshots/testo_meta_tests/fccf02a5c37e/stdxxx

`./test status --autoclean` or `./test run --autoclean` will delete snapshot folders that don't belong to any known test. This usually happens when a test is renamed or recategorized.
Closes #102 
PR checklist:

Add '--autoclean' option to delete dead snapshots
